<script setup>
// Registers as the theme's native search extension point (see VPNavbar.vue:
// it renders a globally-registered 'SearchBox' component automatically, the
// same slot @vuepress/plugin-search and @vuepress/plugin-docsearch use).
//
// Index is generated by scripts/build-search-index.mjs from the real docs/**
// content (titles, H2s, an excerpt) — not hardcoded. Fuzzy matching via
// Fuse.js. Recent searches persist in localStorage; popular searches are a
// small curated seed list (no real usage data exists yet to derive this from
// honestly — replace once the site has traffic).
import { ref, computed, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { useRouter, withBase } from 'vuepress/client'
import Fuse from 'fuse.js'

const RECENT_KEY = 'immac-recent-searches'
const MAX_RECENT = 6

const POPULAR_SEARCHES = [
  'Flexbox',
  'Grid',
  'Semantic HTML',
  'Git and GitHub setup',
  'Accessibility',
  'Box model',
]

const router = useRouter()
const query = ref('')
const open = ref(false)
const activeIndex = ref(-1)
const index = ref([])
const fuse = ref(null)
const rootEl = ref(null)
const inputEl = ref(null)

const recent = ref([])
function loadRecent() {
  try {
    const raw = localStorage.getItem(RECENT_KEY)
    recent.value = raw ? JSON.parse(raw) : []
  } catch {
    recent.value = []
  }
}
function pushRecent(term) {
  const trimmed = term.trim()
  if (!trimmed) return
  const next = [trimmed, ...recent.value.filter((r) => r.toLowerCase() !== trimmed.toLowerCase())]
  recent.value = next.slice(0, MAX_RECENT)
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(recent.value))
  } catch {
    // storage unavailable (private browsing, quota) — recent search just
    // won't persist across visits, not worth surfacing to the student
  }
}

const results = computed(() => {
  if (!query.value.trim() || !fuse.value) return []
  return fuse.value.search(query.value.trim()).slice(0, 8).map((r) => r.item)
})

// Flat list driving keyboard navigation — mirrors whatever sections are
// currently visible, in display order.
const flatItems = computed(() => {
  if (query.value.trim()) {
    return results.value.map((item) => ({ kind: 'result', item }))
  }
  const items = []
  for (const term of recent.value) items.push({ kind: 'recent', term })
  for (const term of POPULAR_SEARCHES) items.push({ kind: 'popular', term })
  return items
})

async function loadIndex() {
  try {
    const res = await fetch(withBase('/search-index.json'))
    index.value = await res.json()
    fuse.value = new Fuse(index.value, {
      keys: [
        { name: 'title', weight: 0.5 },
        { name: 'headings', weight: 0.3 },
        { name: 'excerpt', weight: 0.2 },
      ],
      threshold: 0.38,
      ignoreLocation: true,
    })
  } catch {
    index.value = []
  }
}

function openDropdown() {
  open.value = true
  activeIndex.value = -1
}
function closeDropdown() {
  open.value = false
  activeIndex.value = -1
}

function go(route, term) {
  pushRecent(term)
  closeDropdown()
  query.value = ''
  router.push(route)
}

function runTermSearch(term) {
  query.value = term
  nextTick(() => inputEl.value?.focus())
}

function onKeydown(e) {
  if (e.key === 'Escape') {
    closeDropdown()
    inputEl.value?.blur()
    return
  }
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    if (!open.value) openDropdown()
    activeIndex.value = Math.min(activeIndex.value + 1, flatItems.value.length - 1)
    return
  }
  if (e.key === 'ArrowUp') {
    e.preventDefault()
    activeIndex.value = Math.max(activeIndex.value - 1, 0)
    return
  }
  if (e.key === 'Enter') {
    e.preventDefault()
    const active = flatItems.value[activeIndex.value]
    if (active) {
      if (active.kind === 'result') go(active.item.route, query.value)
      else runTermSearch(active.term)
    } else if (query.value.trim() && results.value[0]) {
      go(results.value[0].route, query.value)
    }
  }
}

function onClickOutside(e) {
  if (rootEl.value && !rootEl.value.contains(e.target)) closeDropdown()
}

onMounted(() => {
  loadRecent()
  loadIndex()
  document.addEventListener('click', onClickOutside)
})
onBeforeUnmount(() => {
  document.removeEventListener('click', onClickOutside)
})
</script>

<template>
  <div ref="rootEl" class="search-box" :class="{ 'is-open': open }">
    <div class="search-field">
      <svg class="search-icon" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">
        <circle cx="9" cy="9" r="6" /><path d="M17 17l-4-4" />
      </svg>
      <input
        ref="inputEl"
        v-model="query"
        type="text"
        role="combobox"
        aria-label="Search the course content"
        :aria-expanded="open"
        aria-controls="search-listbox"
        aria-autocomplete="list"
        :aria-activedescendant="activeIndex > -1 ? 'search-option-' + activeIndex : undefined"
        placeholder="Search the course content"
        @focus="openDropdown"
        @keydown="onKeydown"
      />
    </div>

    <div v-if="open" id="search-listbox" role="listbox" aria-label="Search suggestions" class="search-dropdown">
      <template v-if="!query.trim()">
        <div v-if="recent.length" class="search-section" role="group" aria-label="Recent searches">
          <div class="search-section-label">Recent searches</div>
          <button
            v-for="(term, i) in recent"
            :id="'search-option-' + i"
            :key="'recent-' + term"
            type="button"
            role="option"
            :aria-selected="i === activeIndex"
            class="search-row search-row-term"
            :class="{ 'is-active': i === activeIndex }"
            @click="runTermSearch(term)"
            @mouseenter="activeIndex = i"
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M8 4v4l2.5 2.5M14 8A6 6 0 1 1 8 2" /></svg>
            {{ term }}
          </button>
        </div>

        <div class="search-section" role="group" aria-label="Popular searches">
          <div class="search-section-label">Popular searches</div>
          <button
            v-for="(term, i) in POPULAR_SEARCHES"
            :id="'search-option-' + (recent.length + i)"
            :key="'popular-' + term"
            type="button"
            role="option"
            :aria-selected="(recent.length + i) === activeIndex"
            class="search-row search-row-term"
            :class="{ 'is-active': (recent.length + i) === activeIndex }"
            @click="runTermSearch(term)"
            @mouseenter="activeIndex = recent.length + i"
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M8 2l1.8 3.7 4 .6-2.9 2.9.7 4-3.6-1.9-3.6 1.9.7-4L2.2 6.3l4-.6z" /></svg>
            {{ term }}
          </button>
        </div>
      </template>

      <template v-else>
        <div class="search-section" role="group" aria-label="Results">
          <div class="search-section-label">Results</div>
          <button
            v-for="(item, i) in results"
            :id="'search-option-' + i"
            :key="item.route"
            type="button"
            role="option"
            :aria-selected="i === activeIndex"
            class="search-row search-row-result"
            :class="{ 'is-active': i === activeIndex }"
            @click="go(item.route, query)"
            @mouseenter="activeIndex = i"
          >
            <span class="sr-title">{{ item.title }}</span>
            <span class="sr-excerpt">{{ item.excerpt }}</span>
          </button>
          <div v-if="!results.length" class="search-empty" role="status">No pages match "{{ query }}".</div>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.search-box {
  position: relative;
  font-family: var(--font-ui, -apple-system, sans-serif);
  margin-inline-start: 0.75rem;
}

.search-field {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  height: 2.1rem;
  padding-inline: 0.65rem;
  border: 1px solid var(--vp-c-border, #d4d4d4);
  border-radius: 6px;
  background: var(--vp-c-bg, #fff);
  transition: border-color 150ms ease;
}
.search-box.is-open .search-field {
  border-color: var(--vp-c-accent, #006341);
}

.search-icon {
  width: 0.95rem;
  height: 0.95rem;
  color: var(--vp-c-text-mute, #5f5f5f);
  flex-shrink: 0;
}

.search-field input {
  border: none;
  outline: none;
  background: transparent;
  font: inherit;
  font-size: 0.85rem;
  color: var(--vp-c-text, #212721);
  width: 12rem;
}
.search-field input:focus-visible {
  outline: 2px solid var(--vp-c-accent, #006341);
  outline-offset: 2px;
  border-radius: 3px;
}
.search-row:focus-visible {
  outline: 2px solid var(--vp-c-accent, #006341);
  outline-offset: -2px;
}
.search-field input::placeholder {
  color: var(--vp-c-text-subtle, #6b6b6b);
}

.search-dropdown {
  position: absolute;
  top: calc(100% + 0.4rem);
  right: 0;
  width: 22rem;
  max-width: min(22rem, 90vw);
  max-height: 26rem;
  overflow-y: auto;
  /* Backstop. Nothing inside should be wider than the dropdown now, but a
     result is arbitrary content and this keeps a long unbroken string from
     pushing the panel sideways. */
  overflow-x: hidden;
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-border, #d4d4d4);
  border-radius: 8px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
  padding: 0.4rem;
  z-index: 60;
}

.search-section + .search-section {
  margin-top: 0.3rem;
  padding-top: 0.4rem;
  border-top: 1px solid var(--vp-c-divider, #e4e4e4);
}

.search-section-label {
  font-size: 0.66rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--vp-c-text-mute, #5f5f5f);
  padding: 0.35rem 0.5rem 0.2rem;
}

.search-row {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  text-align: left;
  border: none;
  background: transparent;
  border-radius: 5px;
  padding: 0.45rem 0.55rem;
  font: inherit;
  font-size: 0.84rem;
  color: var(--vp-c-text, #212721);
  cursor: pointer;
}
.search-row svg {
  width: 0.85rem;
  height: 0.85rem;
  color: var(--vp-c-text-subtle, #6b6b6b);
  flex-shrink: 0;
}
.search-row.is-active,
.search-row:hover {
  background: var(--accent-soft, #e5efec);
}

.search-row-result {
  flex-direction: column;
  align-items: flex-start;
  gap: 0.15rem;
  /* A flex child defaults to min-width: auto, which refuses to shrink below
     its content. The excerpt is one unbroken line, so the row grew wider than
     the dropdown and the text ran out the right edge. The line-clamp below
     could not help: it clips lines, and an unconstrained box only ever has
     one. Both of these have to be here for the clamp to do anything at all. */
  min-width: 0;
}

.sr-title,
.sr-excerpt {
  max-width: 100%;
  min-width: 0;
}

.sr-title {
  font-weight: 600;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.sr-excerpt {
  width: 100%;
  font-size: 0.74rem;
  color: var(--vp-c-text-mute, #5f5f5f);
  /* Was display: -webkit-box with -webkit-line-clamp: 1. Measured on the
     built site, display computed to flow-root, so the clamp never engaged
     and a constrained excerpt was hard-cut mid-word with no ellipsis. For a
     single line the ordinary truncation below does the same job without
     depending on a display mode surviving the build, and it matches how
     .sr-title already truncates. */
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.search-empty {
  padding: 0.6rem 0.55rem;
  font-size: 0.82rem;
  color: var(--vp-c-text-mute, #5f5f5f);
}

@media (max-width: 719px) {
  .search-field input { width: 8rem; }
  .search-dropdown { width: 90vw; right: -2rem; }
}
</style>
